// -----------------------------------------------------------------------------
// Vehicle-Detail stylesheet — extracted from the monolithic
// `/app/frontend/app/(app)/vehicle/[id].tsx` during the P1
// modularization pass (Aug 2026). ZERO logic was touched — this is a
// verbatim copy of the original 2550-line `makeStyles` block, moved
// out to give the route file breathing room and to unblock further
// per-modal refactors.
//
// If you're editing styles here:
//   • Keep this file the ONLY source of truth for vehicle-detail
//     styles — the route file, its subcomponents (`DetailRow`,
//     `HeroPill`, `ReportResultBody`, `CollapsibleSection`) and any
//     future modal splits should all `import { makeStyles } from
//     "@/src/styles/vehicleDetailStyles"`.
//   • Every entry is theme-aware via the `colors: Palette` argument
//     — never hardcode hex values inside the returned object.
// -----------------------------------------------------------------------------
import { StyleSheet, Platform } from "react-native";
import { spacing, radius, fonts } from "@/src/theme";
import { type Palette } from "@/src/theme/ThemeContext";

export const makeStyles = (colors: Palette) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.paper,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  deleteBtn: { padding: 4 },
  backBtn: { padding: 4 },
  headerTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "700",
    fontFamily: fonts.heading,
    flex: 1,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  // ScrollView content — capped to a readable column width on desktop
  // so label/value pairs (e.g. "Year Registered: 2023") sit close
  // together instead of stretching to opposite edges of a 1440-px
  // viewport. Mobile stays 100% width because it's below the cap.
  scroll: {
    padding: spacing.lg,
    paddingBottom: 120,
    width: "100%",
    maxWidth: 820,
    alignSelf: "center",
  },

  // Red PDF badge — used on the "Download Valuation PDF" button to make
  // the download action obviously document-based (per user request).
  pdfBadge: {
    backgroundColor: "#E31C24",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  pdfBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },

  // Wrapper card that ties the Fourbuy Offer banner together with the
  // nested Fourbuy Offer History collapsible below it. Keeps them
  // visually linked as a single "offer" unit.
  fourbuyOfferCard: {
    marginBottom: spacing.md,
    borderRadius: radius.lg,
    overflow: "hidden",
  },
  nestedHistory: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.paper,
  },
  nestedHistoryToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
  },
  nestedHistoryTitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  nestedHistoryBody: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
  },

  // Collapsible toggle row on the Fourbuy Offer History card.
  priceHistoryToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 4,
  },

  // Small "peek" caption under the Cover Offers Received header when
  // the panel is collapsed — shows the highest cover as a preview.
  coverOffersPeek: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },

  // Combined advisory shown below the AutoTrader + WeBuyCars deep-link
  // cards. Explains how the two markets differ so the dealer doesn't
  // treat them as apples-to-apples.
  compareAdvisory: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: spacing.sm,
    padding: spacing.sm + 2,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  // Container for the AutoTrader + WeBuyCars comparison cards. Uses
  // flex-wrap so on narrow viewports (< ~640px total row width) the
  // second card wraps under the first — matching the historical
  // mobile-stacked layout. On wider screens both cards share the row
  // 50/50 thanks to their own `flex: 1` inside.
  compareCardsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    alignItems: "stretch",
  },
  compareAdvisoryText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  // ----- "Subject to View" advisory banner (top of detail page) -----
  unseenBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    padding: spacing.sm + 2,
    marginBottom: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  unseenBannerTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  unseenBannerHint: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
    lineHeight: 15,
  },

  // -------- Dealer banner (submitter profile + cover + dealership) --------
  // On desktop the containing column can be extremely wide, which used
  // to stretch the cover banner into a shallow ~11:1 strip. We now
  // constrain the banner to a phone-friendly max width and use a
  // proper aspect ratio so the cover photo keeps its natural shape on
  // every viewport (mobile, tablet, desktop).
  dealerBanner: {
    marginBottom: spacing.md,
    marginHorizontal: spacing.md,
    position: "relative",
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
  },
  dealerBannerCoverClip: {
    width: "100%",
    // 16:9 matches the admin upload crop + the profile banner across
    // every platform so the picture is never partially cropped away.
    aspectRatio: 16 / 9,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    overflow: "hidden",
  },
  dealerBannerCover: {
    width: "100%",
    height: "100%",
  },
  dealerBannerCoverEmpty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.paper,
  },
  dealerBannerAvatarWrap: {
    position: "absolute",
    left: spacing.md,
    bottom: -22,
    padding: 3,
    backgroundColor: colors.bg,
    borderRadius: 40,
    zIndex: 2,
    ...(Platform.OS === "web"
      ? ({ boxShadow: "0 2px 6px rgba(0,0,0,0.15)" } as any)
      : { elevation: 3 }),
  },
  dealerBannerAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  dealerBannerAvatarFallback: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  dealerBannerBody: {
    paddingLeft: 88,
    paddingRight: spacing.md,
    paddingTop: 8,
    paddingBottom: 4,
    gap: 2,
    minHeight: 30,
  },
  dealerBannerName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  dealerBannerJob: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  dealerBannerCompany: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  // Reference badge — high-contrast, clean mono readout
  refBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    marginBottom: spacing.md,
  },
  refBadgeLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  refBadgeValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
    fontFamily: fonts.mono,
    letterSpacing: 1,
  },

  // "Submitted by" chip
  submittedByChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.paper,
    marginBottom: spacing.md,
  },
  submittedByText: { color: colors.textSecondary, fontSize: 12, flex: 1 },
  submittedByBold: { color: colors.text, fontWeight: "700" },

  // Hero average rating
  heroBox: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    alignItems: "center",
  },
  heroLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: spacing.sm,
  },
  heroInfoBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  heroInfoText: { color: colors.textSecondary, fontSize: 11, fontWeight: "700", letterSpacing: 0.4 },
  heroRow: { flexDirection: "row", alignItems: "baseline" },
  heroValue: {
    color: colors.text,
    fontSize: 64,
    fontWeight: "900",
    fontFamily: fonts.mono,
    letterSpacing: -1,
    lineHeight: 68,
  },
  heroOutOf: {
    color: colors.textSecondary,
    fontSize: 20,
    fontWeight: "700",
    fontFamily: fonts.mono,
    marginLeft: 4,
  },
  heroBar: {
    height: 6,
    backgroundColor: colors.border,
    borderRadius: 3,
    marginTop: spacing.md,
    width: "100%",
    overflow: "hidden",
  },
  heroBarFill: { height: "100%", backgroundColor: colors.primary },
  unseenHeroCaption: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: spacing.md,
    textAlign: "center",
    lineHeight: 16,
    letterSpacing: 0.2,
  },
  heroBreakdown: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.md,
    width: "100%",
    justifyContent: "space-between",
  },
  heroPill: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    backgroundColor: colors.paper,
  },
  heroPillLabel: { color: colors.textSecondary, fontSize: 10, fontWeight: "800", letterSpacing: 1 },
  heroPillValue: { color: colors.text, fontSize: 13, fontWeight: "800", fontFamily: fonts.mono, marginTop: 2 },

  priceBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: spacing.lg,
  },
  priceLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: "700", letterSpacing: 0.5 },
  priceValue: { color: colors.text, fontSize: 30, fontWeight: "800", fontFamily: fonts.number, fontVariant: ["tabular-nums"], letterSpacing: -0.3, marginTop: 4 },
  priceNotes: { color: colors.textSecondary, fontSize: 13, marginTop: 4 },
  pendingBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.lg,
  },
  pendingText: { color: colors.textSecondary, fontWeight: "700", letterSpacing: 0.5, fontSize: 13 },

  // Price history log
  priceHistoryBox: {
    marginBottom: spacing.md,
  },
  // Cover Offers Received (Pricing Agents)
  coverOffersBox: {
    marginBottom: spacing.md,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
  },
  coverOffersHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  coverOffersTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  coverOffersSub: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
    marginBottom: spacing.sm,
  },
  // Bottom-of-list legal disclaimer for cover offers — reminds the
  // dealer that a cover is contingent on a physical inspection and
  // that they should confirm with the covering dealer before
  // proceeding. Rendered as an icon-led paragraph inside a tinted
  // rounded box so it reads as a formal notice rather than just
  // small print.
  coverOffersDisclaimer: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: spacing.sm,
    padding: spacing.sm + 2,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  coverOffersDisclaimerText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    fontStyle: "italic",
  },
  coverOfferRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  // Round profile photo shown at the head of each cover row.
  coverOfferAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  coverOfferAvatarFallback: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary + "22",
    borderWidth: 1,
    borderColor: colors.primary + "55",
  },
  coverOfferAvatarInitial: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: "800",
  },
  coverOfferPrice: {
    color: colors.text,
    fontSize: 17,
    fontWeight: "800",
    fontFamily: fonts.number,
    fontVariant: ["tabular-nums"],
  },
  coverOfferAgent: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  coverOfferDate: {
    color: colors.textDisabled,
    fontSize: 10,
    fontFamily: fonts.mono,
    marginTop: 2,
  },
  coverOfferNote: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 4,
    fontStyle: "italic",
  },
  coverOfferPhone: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: fonts.mono,
  },
  whatsappBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#25D366",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.sm,
  },
  whatsappBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  // -------- Deal Tracking & Profit Analysis (dealer + admin only) --------
  dealBox: {
    // Match the width of the sibling Dealer Offer card above — the
    // parent scroll's padding already provides horizontal insets, so
    // no extra `marginHorizontal` is needed here. `marginTop` gives
    // clear vertical separation from the Dealer Offer card.
    marginTop: spacing.md,
    marginBottom: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    gap: spacing.sm,
  },
  dealHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dealTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: -0.1,
  },
  dealSub: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 1,
    lineHeight: 15,
  },
  dealBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  dealBadgeText: {
    color: colors.textSecondary,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  // Tri-state outcome pill (PENDING · DEAL DONE · NO DEAL DONE)
  dealOutcomePill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radius.pill,
  },
  dealOutcomePillText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  dealOutcomePending: {
    backgroundColor: "#B67900", // amber — awaiting a decision
  },
  dealOutcomeOk: {
    backgroundColor: "#1F7A3A", // green — deal done
  },
  dealOutcomeNo: {
    backgroundColor: "#5A5A5F", // neutral grey — deal not done
  },
  dealStage: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.sm,
    gap: 10,
  },
  dealStageHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dealStagePill: {
    width: 22, height: 22, borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  dealStagePillText: {
    color: colors.onPrimary,
    fontSize: 11,
    fontWeight: "800",
  },
  dealStageTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: -0.1,
  },
  dealChoiceRow: {
    flexDirection: "row",
    gap: 8,
  },
  dealChoiceBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  dealChoiceBtnYes: {
    borderColor: "#1F7A3A",
    backgroundColor: "#1F7A3A",
  },
  dealChoiceBtnNo: {
    borderColor: "#6B7280",
    backgroundColor: "#6B7280",
  },
  dealChoiceBtnPending: {
    // Amber = "no decision yet" — matches the outcome pill at the top
    // so the two visual signals stay in sync.
    borderColor: "#B67900",
    backgroundColor: "#B67900",
  },
  dealChoiceBtnText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  dealChoiceBtnTextActive: {
    color: "#fff",
  },
  dealField: {
    gap: 4,
  },
  dealFieldLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  dealInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    backgroundColor: colors.paper,
    paddingHorizontal: 10,
  },
  dealInputPrefix: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "800",
    marginRight: 6,
  },
  dealInput: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
    paddingVertical: 10,
    fontVariant: ["tabular-nums"],
  },
  dealMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
  },
  dealPnl: {
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: 6,
  },
  dealPnlOk: {
    borderColor: "#1F7A3A" + "66",
    backgroundColor: "#1F7A3A" + "1A",
  },
  dealPnlLoss: {
    borderColor: "#B3261E" + "66",
    backgroundColor: "#B3261E" + "1A",
  },
  dealPnlNeutral: {
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  dealPnlRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dealPnlDivider: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 6,
    marginTop: 2,
  },
  dealPnlLbl: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  dealPnlVal: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  dealPnlProfitRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
    marginTop: 4,
    alignItems: "flex-end",
  },
  dealPnlProfitLbl: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  dealPnlProfitVal: {
    color: "#1F7A3A",
    fontSize: 22,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
    letterSpacing: -0.4,
  },
  dealPnlProfitValLoss: {
    color: "#B3261E",
  },
  dealPnlMargin: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
    fontWeight: "600",
  },
  dealPdfBtn: {
    marginTop: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: radius.sm,
    backgroundColor: colors.text,
  },
  dealPdfBtnText: {
    color: colors.onPrimary,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  // Secondary (outlined) style for the Reconditioning Sheet button —
  // sits directly below the primary Profit Analysis PDF button so both
  // downloads share the same footprint without competing for the eye.
  dealReconBtn: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  // Assign Suppliers pill — outlined primary-tinted button that lives
  // directly above the Reconditioning Sheet download so the dealer sees
  // it as the natural pre-flight step (pick who does the work → download
  // the sheet). Compact width so it doesn't compete visually with the
  // full-width PDF buttons below it.
  assignSuppliersPill: {
    marginTop: spacing.sm,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primary + "55",
    backgroundColor: colors.primary + "18",
  },
  assignSuppliersPillText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "800" as const,
    letterSpacing: 0.3,
  },
  // "Update Profit Analysis" save button — replaces the on-blur autosave
  // so the dealer explicitly commits their edits.
  dealSaveBtn: {
    marginTop: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 13,
    borderRadius: radius.sm,
    borderWidth: 1,
  },

  // ---- Standalone Dealer Offer card ----
  // Sits above the Deal Tracking section. Visible to every user on
  // the owning dealership + admins. Only managerial users (pricing
  // agents) can edit — everyone else sees the current amount and a
  // read-only helper line.
  dealerOfferCard: {
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    gap: 4,
  },
  dealerOfferHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dealerOfferTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: -0.2,
    flex: 1,
  },
  dealerOfferPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#1F7A3A",
  },
  dealerOfferPillText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
  },
  dealerOfferBigNumber: {
    fontSize: 26,
    fontWeight: "900",
    color: colors.text,
    marginTop: 4,
    letterSpacing: -0.5,
  },
  dealerOfferMeta: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textSecondary,
    marginTop: -2,
  },
  dealerOfferHelp: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 17,
    marginTop: 6,
  },
  dealerOfferInputRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    alignItems: "stretch",
  },
  dealerOfferInput: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
    borderRadius: radius.sm,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === "web" ? 12 : 10,
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
    ...(Platform.OS === "web" ? ({ outlineStyle: "none" as any } as any) : {}),
  },
  dealerOfferSaveBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 110,
  },
  dealerOfferSaveBtnText: {
    color: colors.onPrimary,
    fontWeight: "900",
    fontSize: 12,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dealerOfferHistoryToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  dealerOfferHistoryToggleText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 0.3,
  },
  dealerOfferHistoryList: {
    marginTop: 6,
    gap: 6,
  },
  dealerOfferHistoryRow: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    padding: 10,
    backgroundColor: colors.bg,
  },
  dealerOfferHistoryAmount: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  dealerOfferHistoryMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  dealSaveBtnPrimary: {
    backgroundColor: "#1F7A3A",
    borderColor: "#1F7A3A",
  },
  dealSaveBtnSaved: {
    backgroundColor: colors.paper,
    borderColor: colors.border,
  },
  dealSaveBtnText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  // Cover-placement bottom bar (pricing-agent mode)
  coverPlaceBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: spacing.md,
    borderTopWidth: 1,
    backgroundColor: colors.card,
    borderTopColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  coverPlacedTitle: {
    color: colors.success,
    fontWeight: "800",
    fontSize: 15,
  },
  coverPlacedSub: {
    color: colors.textDisabled,
    fontSize: 11,
    marginTop: 2,
  },
  coverInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 15,
    fontWeight: "700",
    color: colors.text,
    backgroundColor: colors.background,
  },
  coverBillNote: {
    color: colors.textDisabled,
    fontSize: 10,
    marginTop: 4,
  },
  coverBtn: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 120,
  },
  coverBtnText: {
    color: colors.onPrimary,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  // Stacked vertically: Decline sits directly above Place Cover so
  // both live in the same right-hand column and the label + colour
  // contrast make the primary/destructive choice obvious.
  coverBtnRow: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "center",
    gap: 8,
  },
  coverDeclineBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: radius.sm,
    backgroundColor: "#DC2626",
    minWidth: 120,
  },
  coverDeclineBtnText: {
    color: "#fff",
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  priceHistoryRow: {
    flexDirection: "row",
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  priceHistoryDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.text,
    marginTop: 6,
  },
  priceHistoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  priceHistoryAction: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  priceHistoryDate: {
    color: colors.textDisabled,
    fontSize: 10,
    fontFamily: fonts.mono,
  },
  priceHistoryPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  priceHistoryOld: {
    color: colors.textSecondary,
    fontSize: 13,
    fontFamily: fonts.number,
    fontVariant: ["tabular-nums"],
    textDecorationLine: "line-through",
  },
  priceHistoryNew: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
    fontFamily: fonts.number,
    fontVariant: ["tabular-nums"],
  },
  priceHistoryDelta: {
    fontSize: 11,
    fontWeight: "700",
    fontFamily: fonts.number,
    fontVariant: ["tabular-nums"],
    marginLeft: 4,
  },
  priceHistoryComment: {
    color: colors.text,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  priceHistoryAdmin: {
    color: colors.textDisabled,
    fontSize: 10,
    marginTop: 4,
    fontStyle: "italic",
  },

  // Declined state (dealer view)
  declinedBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  declinedIconWrap: {
    paddingTop: 2,
  },
  declinedLabel: {
    color: colors.text,
    fontWeight: "800",
    letterSpacing: 1.3,
    fontSize: 12,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  declinedBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  declinedMeta: {
    color: colors.textDisabled,
    fontSize: 11,
    marginTop: 6,
    fontFamily: fonts.mono,
  },

  // "Cannot Offer" admin footer button
  declineBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    borderRadius: radius.md,
    gap: 6,
    minWidth: 130,
  },
  declineBtnText: {
    color: colors.text,
    fontWeight: "800",
    letterSpacing: 0.8,
    fontSize: 13,
    textTransform: "uppercase",
  },

  // Decline modal — dealer-facing quote block
  declineQuote: {
    borderLeftWidth: 3,
    borderLeftColor: colors.text,
    paddingLeft: spacing.sm,
    paddingVertical: 8,
    marginVertical: spacing.sm,
  },
  declineQuoteText: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 19,
    fontStyle: "italic",
  },

  // Reports & Documents section
  reportsSection: {
    marginBottom: spacing.lg,
  },
  reportsSubhead: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginTop: spacing.md,
    marginBottom: 4,
  },
  reportsHelp: {
    color: colors.textDisabled,
    fontSize: 12,
    marginBottom: spacing.sm,
    lineHeight: 17,
  },
  docBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    marginBottom: spacing.sm,
  },
  docBtnLeft: { flexDirection: "row", alignItems: "center", flex: 1, marginRight: spacing.sm },
  docBtnTitle: { color: colors.text, fontSize: 15, fontWeight: "700" },
  docBtnSubtitle: { color: colors.textSecondary, fontSize: 12, marginTop: 2, lineHeight: 16 },
  docBtnDisabled: { opacity: 0.5 },
  reportCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    marginBottom: spacing.sm,
  },
  reportName: { color: colors.text, fontSize: 14, fontWeight: "700", lineHeight: 18 },
  reportCost: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
    fontFamily: fonts.number,
    fontVariant: ["tabular-nums"],
  },
  reportStatusRow: { marginTop: 8 },
  statusPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.pill,
    borderWidth: 1,
    marginBottom: 4,
  },
  statusPillPending: { borderColor: colors.warning + "77", backgroundColor: colors.warning + "1A" },
  statusPillOk: { borderColor: colors.success + "77", backgroundColor: colors.success + "1A" },
  statusPillText: { fontSize: 10, fontWeight: "800", letterSpacing: 1.1 },
  reportPendingNote: { color: colors.textDisabled, fontSize: 11, lineHeight: 15 },
  reportOrderedBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radius.sm,
  },
  reportOrderedBadgeText: { color: colors.text, fontSize: 11, fontWeight: "700", marginLeft: 4, letterSpacing: 0.5 },
  orderBtn: {
    backgroundColor: colors.text,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radius.sm,
    minWidth: 80,
    alignItems: "center",
  },
  orderBtnText: { color: colors.onPrimary, fontWeight: "800", letterSpacing: 1, fontSize: 12, textTransform: "uppercase" },

  // Report confirmation modal
  reportModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.lg,
  },
  reportModalCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: colors.paper,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
  },
  reportModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  reportModalTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
    marginLeft: 8,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  reportModalReport: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "700",
    marginTop: spacing.sm,
  },
  reportModalPrice: {
    color: colors.text,
    fontSize: 32,
    fontWeight: "800",
    fontFamily: fonts.number,
    fontVariant: ["tabular-nums"],
    marginTop: 4,
    marginBottom: spacing.sm,
  },
  reportModalBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: spacing.xs,
  },
  reportModalBodySmall: {
    color: colors.textDisabled,
    fontSize: 12,
    marginBottom: spacing.md,
  },
  reportModalActions: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  reportModalCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  reportModalCancelText: { color: colors.text, fontWeight: "700", letterSpacing: 0.5 },
  reportModalConfirm: {
    flex: 1.4,
    paddingVertical: 14,
    borderRadius: radius.sm,
    backgroundColor: colors.text,
    alignItems: "center",
  },
  reportModalConfirmText: { color: colors.onPrimary, fontWeight: "800", letterSpacing: 1, textTransform: "uppercase" },

  titleBox: {
    marginBottom: spacing.md,
    marginHorizontal: spacing.md,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.md,
    ...(Platform.OS === "web"
      ? ({ boxShadow: "0 2px 8px rgba(0,0,0,0.08)" } as any)
      : { elevation: 1 }),
  },
  titleAccent: {
    width: 5,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  // Make (BMW / Audi / Toyota) is the primary identity of the
  // submission — displayed as a bold, hero-scale heading at the top
  // of the vehicle detail page so dealers can identify the vehicle at
  // a glance. Reads as the visual anchor of the title stack.
  brand: {
    color: colors.text,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 2,
    lineHeight: 32,
  },
  model: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.4,
    lineHeight: 26,
    marginTop: 2,
  },
  derivative: {
    color: colors.text,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: -0.3,
    lineHeight: 24,
    marginTop: 4,
    opacity: 0.92,
  },
  titleYear: {
    marginTop: 8,
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
    fontVariant: ["tabular-nums"],
  },
  titleYearSep: {
    color: colors.textDisabled,
    fontWeight: "500",
  },

  // Vertical detail list — used for Vehicle Details, Condition, etc.
  detailsList: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.md,
  },
  detailRowLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 0.1,
  },
  detailRowValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.1,
    flex: 1,
    textAlign: "right",
  },

  grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  gridItem: {
    width: "31%",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.sm,
    gap: 4,
  },
  gridLabel: { color: colors.textSecondary, fontSize: 10, fontWeight: "700", letterSpacing: 1 },
  gridValue: { color: colors.text, fontSize: 13, fontWeight: "700" },

  sectionTitle: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.4,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  // ─── Collapsible section styles ─────────────────────────────────────
  collapsibleWrap: {
    marginTop: spacing.md,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    overflow: "hidden",
  },
  collapsibleHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    minHeight: 52,
    gap: spacing.sm,
  },
  collapsibleTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  collapsibleSummary: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  collapsibleBody: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    paddingTop: 0,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  // ────────────────────────────────────────────────────────────────────

  infoCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    gap: 6,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.md,
  },
  infoLabel: { color: colors.textSecondary, fontSize: 11, fontWeight: "700", letterSpacing: 1, minWidth: 110 },
  infoValue: { color: colors.text, fontSize: 13, fontWeight: "700", flex: 1, textAlign: "right" },
  infoValueMono: { color: colors.text, fontSize: 12, fontWeight: "700", flex: 1, textAlign: "right", fontFamily: fonts.mono },

  reconRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: colors.border },
  reconCardRow: {
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  reconHeadRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm,
  },
  reconPhotoStripDetail: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  reconThumbWrap: { width: 56, height: 56, borderRadius: radius.sm, overflow: "hidden", borderWidth: 1, borderColor: colors.border },
  reconThumb: { width: "100%", height: "100%" },
  reconLabel: { color: colors.text, fontSize: 13, flex: 1 },
  reconAmount: { color: colors.text, fontSize: 14, fontWeight: "700", fontFamily: fonts.number, fontVariant: ["tabular-nums"] },
  reconTotalRow: { flexDirection: "row", justifyContent: "space-between", paddingTop: spacing.sm, marginTop: 4 },
  reconTotalLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: "700", letterSpacing: 0.5 },
  reconTotalValue: { color: colors.text, fontSize: 18, fontWeight: "800", fontFamily: fonts.number, fontVariant: ["tabular-nums"], letterSpacing: -0.2 },

  photoGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  photoSlot: {
    // Native / narrow web: 2-up square tiles (unchanged).
    // Wide web: fixed 180×135 4:3 tiles matching the admin cockpit layout
    // so the dealer detail page doesn't render photos ~600 px wide.
    width: "48%",
    aspectRatio: 1,
    borderRadius: radius.md,
    overflow: "hidden",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    ...(Platform.OS === "web"
      ? { width: 180, aspectRatio: 4 / 3 } as const
      : {}),
  },
  photoImg: { width: "100%", height: "100%" },
  photoOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  photoLabel: { color: "#fff", fontSize: 11, fontWeight: "800", letterSpacing: 1 },
  photoLabelDim: { color: colors.textDisabled, fontSize: 11, fontWeight: "700", letterSpacing: 1, marginTop: 4 },

  diskBox: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md },
  diskText: { color: colors.text, fontFamily: fonts.mono, fontSize: 12 },
  diskDecodedBox: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    padding: spacing.md,
    gap: 6,
  },
  // Highlighted "1-Owner from new" or "Owned approx. …" badge that sits
  // at the top of the licence-disc data section. Deliberately styled to
  // stand out from the disc-field rows below (larger text, bold weight,
  // strong background + border) so dealers reading the disc data spot
  // the ownership signal immediately.
  ownershipBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.md,
    marginBottom: 6,
    borderWidth: 1.5,
  },
  ownershipBadgeOne: {
    backgroundColor: "#D1FAE5",
    borderColor: "#065F46",
  },
  ownershipBadgeMulti: {
    backgroundColor: colors.paper,
    borderColor: colors.text,
  },
  ownershipBadgeText: {
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  ownershipBadgeTextOne: { color: "#065F46" },
  ownershipBadgeTextMulti: { color: colors.text },
  diskDecodedRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.md,
  },
  diskDecodedLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "500",
    letterSpacing: 0.1,
    minWidth: 110,
  },
  diskDecodedValue: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },

  analysisHeader: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginTop: spacing.lg, marginBottom: spacing.sm },
  analysisTs: { color: colors.textDisabled, fontSize: 11, marginTop: 2 },
  subsectionTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  analysisBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.card,
    minWidth: 90,
    justifyContent: "center",
  },
  analysisBtnText: { color: colors.text, fontWeight: "800", fontSize: 11, letterSpacing: 1 },
  analysisCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md },
  rangeBox: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    overflow: "hidden",
    marginBottom: spacing.md,
  },
  rangeCol: { flex: 1, padding: spacing.sm, alignItems: "center" },
  rangeColMid: { backgroundColor: colors.paper, borderLeftWidth: 1, borderRightWidth: 1, borderColor: colors.border },
  rangeLabel: { color: colors.textSecondary, fontSize: 10, letterSpacing: 1, fontWeight: "700", marginBottom: 4 },
  rangeValue: { color: colors.text, fontSize: 15, fontWeight: "800", fontFamily: fonts.number, fontVariant: ["tabular-nums"], letterSpacing: -0.1 },
  tradeRow: { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.md },
  tradeCol: { flex: 1, padding: spacing.sm, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm },
  tradeLabel: { color: colors.textSecondary, fontSize: 10, letterSpacing: 1, fontWeight: "700", marginBottom: 4 },
  tradeValue: { color: colors.text, fontSize: 17, fontWeight: "800", fontFamily: fonts.number, fontVariant: ["tabular-nums"], letterSpacing: -0.2 },
  summary: { color: colors.text, fontSize: 13, lineHeight: 19, marginBottom: spacing.sm },
  factorsBox: { marginTop: spacing.sm, paddingTop: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, gap: 6 },
  factorsTitle: { color: colors.textSecondary, fontSize: 10, letterSpacing: 1, fontWeight: "700", marginBottom: 4 },
  factorRow: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  factorText: { color: colors.text, fontSize: 12, flex: 1, lineHeight: 17 },
  confidence: { color: colors.textSecondary, fontSize: 11, fontWeight: "700", marginTop: spacing.sm, letterSpacing: 1 },
  disclaimer: { color: colors.textDisabled, fontSize: 11, fontStyle: "italic", marginTop: 4 },
  analysisEmpty: {
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    borderRadius: radius.md,
    backgroundColor: colors.card,
  },
  analysisEmptyText: { color: colors.textSecondary, fontSize: 12, flex: 1, lineHeight: 17 },

  // Tyre estimate section styles
  tyreHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  tyreSpecBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: "#000",
  },
  tyreSpecText: { color: "#fff", fontFamily: fonts.mono, fontSize: 13, fontWeight: "700", letterSpacing: 0.5 },
  tyreRimText: { color: colors.textSecondary, fontSize: 12, fontWeight: "700", letterSpacing: 0.5 }, // legacy — retained for a11y snapshots
  tyreTotalBox: {
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.paper,
    marginBottom: spacing.md,
    alignItems: "center",
  },
  tyreTotalLabel: { color: colors.textSecondary, fontSize: 11, fontWeight: "700", letterSpacing: 0.5 },
  tyreTotalValue: { color: colors.text, fontSize: 28, fontWeight: "800", fontFamily: fonts.number, fontVariant: ["tabular-nums"], letterSpacing: -0.3, marginTop: 4 },

  dealerBox: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md },
  dealerName: { color: colors.text, fontSize: 15, fontWeight: "700" },
  dealerCompany: { color: colors.textSecondary, fontSize: 13, marginTop: 2 },
  dealerEmail: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
  whatsappBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: spacing.md,
    paddingVertical: 12,
    paddingHorizontal: spacing.md,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: "#25D366",
    backgroundColor: "#25D36618",
  },
  whatsappBtnText: { color: "#25D366", fontWeight: "700", fontSize: 14, letterSpacing: 0.5 },

  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: spacing.md,
    backgroundColor: colors.paper,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    gap: spacing.sm,
  },
  priceBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 14,
  },
  priceBtnText: { color: colors.onPrimary, fontWeight: "800", fontSize: 15, letterSpacing: 0.4 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", justifyContent: "flex-end" },
  modalSheet: {
    backgroundColor: colors.paper,
    padding: spacing.lg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
  },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 4 },
  modalTitle: { color: colors.text, fontSize: 20, fontWeight: "800", fontFamily: fonts.heading, letterSpacing: 0.3 },
  modalHint: { color: colors.textSecondary, fontSize: 13, marginBottom: spacing.sm },
  label: { color: colors.textSecondary, fontSize: 13, marginTop: spacing.sm },
  priceInput: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    color: colors.text,
    fontSize: 20,
    fontWeight: "700",
    fontFamily: fonts.mono,
  },
  confirmBtn: {
    marginTop: spacing.md,
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: radius.sm,
    alignItems: "center",
  },
  confirmBtnText: { color: colors.onPrimary, fontWeight: "800", fontSize: 15, letterSpacing: 0.4 },

  // Admin "no reports yet" hint
  adminNoReports: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    marginTop: spacing.sm,
  },
  adminNoReportsText: {
    color: colors.textDisabled,
    fontSize: 12,
    marginLeft: 8,
    flex: 1,
    lineHeight: 16,
  },

  // VIN-Linked report gate — shown when license disk hasn't been captured
  vinRequiredBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm + 2,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
    marginTop: spacing.xs,
  },
  vinRequiredTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
    marginBottom: 4,
  },
  vinRequiredHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  vinRequiredBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    alignSelf: "flex-start",
    marginTop: spacing.sm + 2,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
  },
  vinRequiredBtnText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },

  // Registered-after-discontinued banner on vehicle detail
  discontinuedBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: colors.paper,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.warning,
    padding: spacing.sm + 2,
    marginBottom: spacing.sm,
  },
  discontinuedBannerText: {
    flex: 1,
    color: colors.warning,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },

  // Inline admin pricing block at the bottom of the scroll content.
  adminActionBox: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },

  // Kredo Vehicle Values card — new list price, M&M code, trade + retail.
  marketValuesCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.lg,
  },
  marketRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.sm + 2,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  marketLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  marketValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  marketFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: spacing.sm + 2,
    gap: spacing.sm,
  },
  marketFooterText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 11,
    letterSpacing: 0.3,
  },
  marketRefreshBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
    minWidth: 84,
    justifyContent: "center",
  },
  marketRefreshText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  // Small "locked at valuation" pill — replaces the Refresh CTA once a
  // successful snapshot has been captured, since trade/retail values are
  // fixed at the time of valuation and must not drift.
  marketLockedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  marketLockedText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  marketLoadingBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.md,
  },
  marketLoadingText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  // ---- Bimmervin (BMW factory spec) styles -------------------------------
  bimmerSubHeader: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: spacing.sm,
  },
  bimmerFetchRow: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: spacing.md,
    paddingVertical: spacing.md,
  },
  bimmerFetchTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 2,
  },
  bimmerFetchHint: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
  },
  bimmerFetchBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.neon,
    minWidth: 96,
    justifyContent: "center",
  },
  bimmerFetchBtnText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  bimmerOptionsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: spacing.sm,
  },
  bimmerOptionPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  bimmerOptionKind: {
    color: colors.textSecondary,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  bimmerOptionCode: {
    color: colors.text,
    fontSize: 11,
    fontFamily: fonts.mono,
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  // Rich-row option list variant that shows a description next to each
  // code. Used when the local dictionary yields a human label; codes
  // without a description fall back to the bare (short) row layout.
  bimmerOptionsList: {
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: spacing.sm,
    gap: 6,
  },
  bimmerOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  bimmerOptionRowBare: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: radius.md,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: colors.border,
    backgroundColor: "transparent",
    opacity: 0.72,
  },
  bimmerOptionKindBadge: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: colors.neon + "22",
    minWidth: 22,
    alignItems: "center",
  },
  bimmerOptionKindText: {
    color: colors.text,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  bimmerOptionCodeStrong: {
    color: colors.text,
    fontSize: 12,
    fontFamily: fonts.mono,
    fontWeight: "800",
    letterSpacing: 0.5,
    minWidth: 46,
  },
  bimmerOptionDesc: {
    color: colors.text,
    fontSize: 12,
    lineHeight: 15,
    flex: 1,
  },
  bimmerOptionDescMuted: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
    fontStyle: "italic",
  },
  marketErrorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm + 2,
  },
  marketErrorText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  marketErrorDetail: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
    lineHeight: 16,
  },
  marketHint: {
    color: colors.textSecondary,
    fontSize: 10,
    fontStyle: "italic",
    marginTop: 2,
    letterSpacing: 0.3,
  },
  adminCurrentPrice: {
    backgroundColor: colors.paper,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.sm + 2,
    marginBottom: spacing.xs,
  },
  adminCurrentPriceLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  adminCurrentPriceValue: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginTop: 2,
    fontFamily: fonts.number,
  },

  // Status pill used inside a report card for CarTrust pending/completed
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusPillPending: { backgroundColor: colors.paper, borderColor: colors.warning },
  statusPillOk: { backgroundColor: colors.success, borderColor: colors.success },
  statusPillText: { fontSize: 9, fontWeight: "800", letterSpacing: 1 },
  statusPillTextPending: { color: colors.warning },
  statusPillTextOk: { color: colors.onPrimary },
  reportStatusRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6, flexWrap: "wrap" },
  reportStatusMeta: { color: colors.textSecondary, fontSize: 11, flex: 1 },
  // Compact "Natis Owners Query Pending" chip — sits inline with the
  // status pill so the CarTrust card stays a single-row summary on
  // narrow phone widths. Amber palette for a soft "waiting on data"
  // signal without alarming the dealer.
  cartrustOwnershipChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: (colors as any).warningBorder || "#F4C36B",
    backgroundColor: (colors as any).warningBg || "#FEF3C7",
  },
  cartrustOwnershipChipText: {
    color: (colors as any).warningText || "#78350F",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  // Success variant — flips the amber "pending" chip to green once the
  // NaTIS owners query has been fulfilled by Kredo. Matches other
  // "ready to view" indicators in the app for visual continuity.
  cartrustOwnershipChipReady: {
    borderColor: "#10B981",
    backgroundColor: "#D1FAE5",
  },
  cartrustOwnershipChipTextReady: {
    color: "#065F46",
  },
  viewReportBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.sm,
  },
  viewReportBtnText: { color: colors.onPrimary, fontSize: 12, fontWeight: "800", letterSpacing: 0.5 },
  reportOrderedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radius.sm,
  },
  reportOrderedBadgeText: { color: colors.text, fontSize: 11, fontWeight: "800", letterSpacing: 0.5 },

  // Kredo VIN accident history card
  kredoHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  kredoFetchBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    borderRadius: radius.md,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
    minHeight: 44,
  },
  kredoFetchBtnDisabled: {
    opacity: 0.6,
  },
  kredoFetchBtnText: { color: colors.onPrimary, fontSize: 13, fontWeight: "800", letterSpacing: 0.5 },
  kredoEmpty: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    borderRadius: radius.sm,
    padding: spacing.md,
  },
  kredoEmptyText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  kredoClean: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    padding: spacing.md,
  },
  kredoCleanTitle: { color: colors.text, fontSize: 14, fontWeight: "800" },
  kredoCleanSub: { color: colors.textSecondary, fontSize: 11, marginTop: 2 },
  kredoCountBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.warning,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    marginBottom: spacing.sm,
  },
  kredoCountText: { flex: 1, color: colors.text, fontSize: 13, fontWeight: "800", letterSpacing: 0.5 },
  kredoSource: { color: colors.textSecondary, fontSize: 10, letterSpacing: 1, textTransform: "uppercase" },
  claimCard: {
    backgroundColor: colors.paper,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  claimHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  claimDate: { color: colors.text, fontSize: 14, fontWeight: "800" },
  claimCountry: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  claimVehicle: { color: colors.text, fontSize: 12, marginBottom: 2 },
  claimMeta: { color: colors.textSecondary, fontSize: 11, marginBottom: 6 },
  damageRow: { flexDirection: "row", flexWrap: "wrap", gap: 4, marginTop: 4, marginBottom: 4 },
  damageChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: colors.danger,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  damageChipGlass: { backgroundColor: colors.warning },
  damageChipText: { color: "#fff", fontSize: 9, fontWeight: "800", letterSpacing: 0.5 },
  claimId: {
    color: colors.textDisabled,
    fontSize: 10,
    fontFamily: fonts.mono,
    marginTop: 4,
  },

  // CarTrust PDF report states
  cartrustPending: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    padding: spacing.md,
  },
  cartrustPendingTitle: { color: colors.text, fontSize: 13, fontWeight: "800" },
  cartrustPendingSub: { color: colors.textSecondary, fontSize: 11, marginTop: 2 },
  cartrustReady: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.success,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  cartrustReadyTitle: { color: colors.text, fontSize: 14, fontWeight: "800" },
  cartrustReadySub: { color: colors.textSecondary, fontSize: 11, marginTop: 2 },
  cartrustViewBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 12,
  },
  cartrustViewBtnText: { color: colors.onPrimary, fontWeight: "800", fontSize: 13, letterSpacing: 0.5 },

  // View Report button (delivered)
  viewReportBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.text,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radius.sm,
    minWidth: 80,
    justifyContent: "center",
  },
  viewReportBtnText: {
    color: colors.onPrimary,
    fontWeight: "800",
    letterSpacing: 1,
    fontSize: 12,
    marginLeft: 4,
    textTransform: "uppercase",
  },

  // Report viewer modal
  viewReportCard: {
    width: "100%",
    maxWidth: 520,
    maxHeight: "88%",
    backgroundColor: colors.paper,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
  },
  viewReportHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  viewReportKicker: {
    color: colors.success,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  viewReportTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
    marginTop: 4,
    lineHeight: 20,
  },
  viewReportMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 4,
    fontFamily: fonts.mono,
  },
  viewReportBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  reportSectionHeader: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginTop: spacing.md,
    marginBottom: 6,
  },
  reportRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  reportRowLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
  },
  reportRowValue: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
    flexShrink: 1,
    textAlign: "right",
    maxWidth: "60%",
  },
  reportBullet: {
    color: colors.text,
    fontSize: 12,
    paddingVertical: 3,
    lineHeight: 17,
  },
  serviceHistoryRow: {
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    paddingVertical: spacing.sm,
    gap: 2,
  },
  serviceHistoryHeadRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
  },
  serviceHistoryDate: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  serviceHistoryOdo: {
    color: colors.textSecondary,
    fontSize: 12,
    fontVariant: ["tabular-nums"],
  },
  serviceHistoryRepairer: {
    color: colors.text,
    fontSize: 12,
    marginTop: 2,
  },
  serviceHistoryMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
    marginTop: 2,
  },
  serviceHistoryJob: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  serviceHistoryDetails: {
    color: colors.textSecondary,
    fontSize: 11,
    flex: 1,
    textAlign: "right",
    lineHeight: 15,
  },
  mockBanner: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.md,
    padding: 10,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    backgroundColor: colors.card,
  },
  mockBannerText: {
    color: colors.textDisabled,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginLeft: 6,
    flex: 1,
  },
  reportPdfBtn: {
    marginTop: spacing.sm,
    backgroundColor: colors.text,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: radius.sm,
  },
  reportPdfBtnText: {
    color: colors.onPrimary,
    fontWeight: "800",
    letterSpacing: 1,
    marginLeft: 6,
    textTransform: "uppercase",
    fontSize: 13,
  },
});
